version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
      SECRET_KEY: "secret"
      DEBUG: "True"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached